// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKJm0uLixC__1B6JSpn5FFR1D8O80PtLU',
    appId: '1:875682938754:ios:974db758a98339a216d99b',
    messagingSenderId: '875682938754',
    projectId: 'laundrify-d34c0',
    databaseURL:
        'https://laundrify-d34c0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laundrify-d34c0.firebasestorage.app',
    iosBundleId: 'com.example.lundrify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKJm0uLixC__1B6JSpn5FFR1D8O80PtLU',
    appId: '1:875682938754:ios:974db758a98339a216d99b',
    messagingSenderId: '875682938754',
    projectId: 'laundrify-d34c0',
    databaseURL:
        'https://laundrify-d34c0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laundrify-d34c0.firebasestorage.app',
    iosBundleId: 'com.example.lundrify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUDKRMGAKJ7vnpzky9Z8vfQQruDlhAB0k',
    appId: '1:875682938754:web:287231a25ae5bbfa16d99b',
    messagingSenderId: '875682938754',
    projectId: 'laundrify-d34c0',
    authDomain: 'laundrify-d34c0.firebaseapp.com',
    databaseURL:
        'https://laundrify-d34c0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laundrify-d34c0.firebasestorage.app',
    measurementId: 'G-RN0JDWW2HD',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUDKRMGAKJ7vnpzky9Z8vfQQruDlhAB0k',
    appId: '1:875682938754:web:287231a25ae5bbfa16d99b',
    messagingSenderId: '875682938754',
    projectId: 'laundrify-d34c0',
    authDomain: 'laundrify-d34c0.firebaseapp.com',
    databaseURL:
        'https://laundrify-d34c0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laundrify-d34c0.firebasestorage.app',
    measurementId: 'G-RN0JDWW2HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPje5B76OXD72A4LlHS5qpYTQB-zPxEGc',
    appId: '1:875682938754:android:6d61374bac70832d16d99b',
    messagingSenderId: '875682938754',
    projectId: 'laundrify-d34c0',
    databaseURL:
        'https://laundrify-d34c0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laundrify-d34c0.firebasestorage.app',
  );
}
